version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    #restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    #restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
